let dados = [
  // Volkswagen
  {
    titulo: "Fusca",
    marca: "Volkswagen",
    ano: 1967,
    motor: "1.3",
    potencia: 50,
    descricao: "Um ícone mundial, conhecido por sua simplicidade, durabilidade e design atemporal.",
    link: "https://pt.wikipedia.org/wiki/Volkswagen_Fusca",
    tags: "Fusca clássico popular",
  },
  {
    titulo: "Golf GTI",
    marca: "Volkswagen",
    ano: 2022,
    motor: "2.0 TSI",
    potencia: 245,
    descricao: "Um ícone dos hatches esportivos, com design moderno e performance emocionante.",
    link: "https://pt.wikipedia.org/wiki/Volkswagen_Golf",
    tags: "Golfao GTI hatchback esportivo",
  },
  {
    titulo: "Gol GTI",
    marca: "Volkswagen",
    ano: 1981,
    motor: "1.8",
    potencia: 90,
    descricao: "O primeiro Gol GTI marcou época no Brasil, sendo um dos primeiros hatches esportivos nacionais.",
    link: "https://pt.wikipedia.org/wiki/Volkswagen_Gol",
    tags: "Gol GTI hatch esportivo nacional",
  },
  {
    titulo: "Passat",
    marca: "Volkswagen",
    ano: 1981,
    motor: "1.6",
    potencia: 75,
    descricao: "Um dos sedãs médios mais populares da Europa na década de 1980, conhecido por sua confiabilidade e design quadrado.",
    link: "https://pt.wikipedia.org/wiki/Volkswagen_Passat",
    tags: "Passat sedã clássico",
  },
  {
    titulo: "Jetta",
    marca: "Volkswagen",
    ano: 1980,
    motor: "1.6",
    potencia: 75,
    descricao: "Versão sedã do Golf, o Jetta se tornou um ícone da marca Volkswagen.",
    link: "https://pt.wikipedia.org/wiki/Volkswagen_Jetta",
    tags: "Jetta sedã clássico",
  },


  // Nissan
  {
    titulo: "Skyline GT-R R32",
    marca: "Nissan",
    ano: 1989,
    motor: "RB26DETT",
    potencia: 280,
    descricao: "Uma das primeiras gerações do Skyline GT-R, conhecido por sua tração integral e desempenho excepcional nas pistas.",
    link: "https://pt.wikipedia.org/wiki/Nissan_Skyline",
    tags: "Skyline GT-R R32 JDM esportivo drift",
  },
  {
    titulo: "Skyline GT-R R34",
    marca: "Nissan",
    ano: 1999,
    motor: "RB26DETT",
    potencia: 280,
    descricao: "Um dos carros esportivos japoneses mais icônicos, famoso por sua aparência agressiva e desempenho excepcional.",
    link: "https://pt.wikipedia.org/wiki/Nissan_Skyline",
    tags: "Skyline GT-R R34 JDM esportivo drift",
  },
  {
    titulo: "Fairlady Z",
    marca: "Nissan",
    ano: 1970,
    motor: "L24",
    potencia: 150,
    descricao: "Um dos primeiros esportivos japoneses a fazer sucesso mundialmente, a Fairlady Z é um ícone do design dos anos 70.",
    link: "https://pt.wikipedia.org/wiki/Nissan_Fairlady_Z",
    tags: "Fairlady Z esportivo japonês",
  },
  {
    titulo: "350Z",
    marca: "Nissan",
    ano: 2003,
    motor: "VQ35DE",
    potencia: 287,
    descricao: "Sucessor espiritual da 300ZX, a 350Z conquistou fãs com seu design agressivo e desempenho emocionante.",
    link: "https://pt.wikipedia.org/wiki/Nissan_350Z",
    tags: "350Z esportivo japonês",
  },


  // Toyota
  {
    titulo: "Supra A80",
    marca: "Toyota",
    ano: 1993,
    motor: "2JZ-GTE",
    potencia: 320,
    descricao: "Um clássico dos anos 90, famoso por sua aparição no filme Velozes e Furiosos.",
    link: "https://pt.wikipedia.org/wiki/Toyota_Supra",
    tags: "Supra A80 JDM esportivo turbo",
  },
  {
    titulo: "Corolla AE86",
    marca: "Toyota",
    ano: 1983,
    motor: "4A-GE",
    potencia: 130,
    descricao: "Famoso por sua participação no anime Initial D, o AE86 é um dos carros mais queridos pelos fãs de drift.",
    link: "https://pt.wikipedia.org/wiki/Toyota_Corolla",
    tags: "Corolla AE86 JDM esportivo drift",
  },

  // Ford
  {
    titulo: "Mustang GT",
    marca: "Ford",
    ano: 1967,
    motor: "V8",
    potencia: 300,
    descricao: "Um dos muscle cars mais famosos, com design clássico e desempenho potente.",
    link: "https://pt.wikipedia.org/wiki/Ford_Mustang",
    tags: "Mustang muscle car clássico americano",
  },
  {
    titulo: "Mustang Shelby GT500",
    marca: "Ford",
    ano: 1967,
    motor: "V8",
    potencia: 500,
    descricao: "Uma das versões mais potentes do Mustang, com um design agressivo e desempenho de tirar o fôlego.",
    link: "https://pt.wikipedia.org/wiki/Ford_Mustang",
    tags: "Mustang Shelby GT500 muscle car clássico",
  },

  // Mitsubishi
  {
    titulo: "Lancer Evolution VI",
    marca: "Mitsubishi",
    ano: 1999,
    motor: "4G63",
    potencia: 280,
    descricao: "Um dos carros de rally mais famosos, conhecido por sua tração integral e desempenho em curvas.",
    link: "https://pt.wikipedia.org/wiki/Mitsubishi_Lancer_Evolution",
    tags: "Lancer Evolution rally esportivo",
  },
  {
    titulo: "3000GT VR-4",
    marca: "Mitsubishi",
    ano: 1990,
    motor: "6G72",
    potencia: 320,
    descricao: "Um GT japonês dos anos 90, com um design futurista e motor biturbo.",
    link: "https://pt.wikipedia.org/wiki/Mitsubishi_3000GT",
    tags: "3000GT GT japonês turbo",
  },

  // Porsche
  {
    titulo: "Porsche 911 (964)",
    marca: "Porsche",
    ano: 1989,
    motor: "3.6",
    potencia: 250,
    descricao: "Uma das gerações mais clássicas do 911, com um design atemporal e desempenho esportivo.",
    link: "https://pt.wikipedia.org/wiki/Porsche_911",
    tags: "Porsche 911 clássico esportivo",
  },
  {
    titulo: "Porsche 356 Speedster",
    marca: "Porsche",
    ano: 1955,
    motor: "1.5",
    potencia: 70,
    descricao: "Um dos primeiros modelos da Porsche, conhecido por seu design leve e esportivo.",
    link: "https://pt.wikipedia.org/wiki/Porsche_356",
    tags: "Porsche 356 clássico esportivo",
  },

  // Honda
  {
    titulo: "Civic G10",
    marca: "Honda",
    ano: 1972,
    motor: "1.2",
    potencia: 60,
    descricao: "Primeira geração do Civic, um dos carros mais vendidos do mundo.",
    link: "https://pt.wikipedia.org/wiki/Honda_Civic",
    tags: "Civic G10 hatch compacto",
  },
  {
    titulo: "Civic Type-R",
    marca: "Honda",
    ano: 1997,
    motor: "B18C5",
    potencia: 200,
    descricao: "A primeira geração do Civic Type-R marcou o início de uma linhagem de hatches esportivos de alto desempenho.",
    link: "https://pt.wikipedia.org/wiki/Honda_Civic",
    tags: "Civic Type-R esportivo hatch",
  },

  // Chevrolet
  {
    titulo: "Chevrolet Corvette C2 Stingray",
    marca: "Chevrolet",
    ano: 1963,
    motor: "V8",
    potencia: 300,
    descricao: "Um dos primeiros Corvettes a ganhar fama mundial, com design icônico e desempenho esportivo.",
    link: "https://pt.wikipedia.org/wiki/Chevrolet_Corvette",
    tags: "Corvette C2 Stingray esportivo americano",
  },
  {
    titulo: "Chevrolet Camaro SS",
    marca: "Chevrolet",
    ano: 1969,
    motor: "V8",
    potencia: 396,
    descricao: "Um dos muscle cars mais famosos da história, com design agressivo e desempenho brutal.",
    link: "https://pt.wikipedia.org/wiki/Chevrolet_Camaro",
    tags: "Camaro SS muscle car americano",
  },

  // Dodge
  {
    titulo: "Dodge Challenger Hellcat",
    marca: "Dodge",
    ano: 2015,
    motor: "V8 supercharged",
    potencia: 707,
    descricao: "Um muscle car moderno com potência brutal e design agressivo, revivendo o espírito dos clássicos americanos.",
    link: "https://pt.wikipedia.org/wiki/Dodge_Challenger",
    tags: "Challenger Hellcat muscle car americano",
  },
  {
    titulo: "Dodge Viper SRT10",
    marca: "Dodge",
    ano: 2003,
    motor: "V10",
    potencia: 500,
    descricao: "Um dos esportivos americanos mais poderosos de sua época, com um design exótico e desempenho brutal.",
    link: "https://pt.wikipedia.org/wiki/Dodge_Viper",
    tags: "Viper SRT10 esportivo americano",
  },

  // Ferrari
  {
    titulo: "Ferrari 250 GTO",
    marca: "Ferrari",
    ano: 1962,
    motor: "V12",
    potencia: 300,
    descricao: "Um dos carros de corrida mais valiosos do mundo, com um design atemporal e desempenho excepcional.",
    link: "https://pt.wikipedia.org/wiki/Ferrari_250_GTO",
    tags: "Ferrari 250 GTO carro de corrida clássico",
  },
  {
    titulo: "Ferrari F40",
    marca: "Ferrari",
    ano: 1987,
    motor: "V8 biturbo",
    potencia: 478,
    descricao: "O último Ferrari com aprovação de Enzo Ferrari, com um design radical e desempenho de supercarro.",
    link: "https://pt.wikipedia.org/wiki/Ferrari_F40",
    tags: "Ferrari F40 supercarro clássico",
  },

  // Lamborghini
  {
    titulo: "Lamborghini Miura",
    marca: "Lamborghini",
    ano: 1966,
    motor: "V12",
    potencia: 350,
    descricao: "Um dos primeiros supercarros da história, com design revolucionário e desempenho brutal.",
    link: "https://pt.wikipedia.org/wiki/Lamborghini_Miura",
    tags: "Miura Lamborghini supercarro clássico",
  },
  {
    titulo: "Lamborghini Murciélago",
    marca: "Lamborghini",
    ano: 2001,
    motor: "V12",
    potencia: 580,
    descricao: "Sucessor do Diablo, com design agressivo e desempenho de tirar o fôlego.",
    link: "https://pt.wikipedia.org/wiki/Lamborghini_Murciélago",
    tags: "Murciélago Lamborghini supercarro moderno",
  },
  {
    titulo: "Lamborghini Gallardo",
    marca: "Lamborghini",
    ano: 2003,
    motor: "V10",
    potencia: 500,
    descricao: "Modelo de entrada da Lamborghini, com design elegante e desempenho esportivo.",
    link: "https://pt.wikipedia.org/wiki/Lamborghini_Gallardo",
    tags: "Gallardo Lamborghini supercarro",
  },
  {
    titulo: "Lamborghini Aventador",
    marca: "Lamborghini",
    ano: 2011,
    motor: "V12",
    potencia: 700,
    descricao: "Sucessor do Murciélago, com design futurista e desempenho extremo.",
    link: "https://pt.wikipedia.org/wiki/Lamborghini_Aventador",
    tags: "Aventador Lamborghini supercarro moderno",
  },
  // ... (outros carros)
];